[workspace]
resolver = "2"
members = [
    "create_assistant",
    "retrieve_assistant",
    "modify_assistant",
    "delete_assistant",
    "list_assistants",
    "create_thread_run",
    "threads",
    "messages",
    "runs",
    "run_steps",
    "currency_converter_assistant",
]
