[package]
name = "retrieve_fine_tuning"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
openai_dive = { path = "./../../../openai-client", features = ["download"] }
tokio = { version = "1.0", features = ["full"] }
