pub mod shared;
pub mod model;
pub mod completion;
#[cfg(feature = "stream")]
pub mod completion_stream;
pub mod chat_completion;
#[cfg(feature = "stream")]
pub mod chat_completion_stream;
pub mod edit;
pub mod image;
pub mod embedding;
pub mod audio;
pub mod file;
pub mod fine_tune;
pub mod moderation;
