[package]
name = "deepseek_chat_stream"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
openai_dive = { path = "./../../../openai_dive", features = ["stream"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
ftail = "0.2"
