[package]
name = "prompt"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
openai_dive = { path = "./../../../openai_dive" }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
log = "0.4"
ftail = "0.3"
