pub mod administration;
pub mod assistants;
pub mod audio;
pub mod batch;
pub mod chat;
pub mod embeddings;
pub mod files;
pub mod fine_tuning;
pub mod images;
pub mod models;
pub mod moderations;
#[cfg(feature = "realtime")]
pub mod realtime;
pub mod uploads;
